# Algebra Lineal

In [5]:
import numpy as np
A = np.random.randint((10), size =(4,4))
B = np.random.randint((10), size =(4,4))

In [6]:
A

array([[6, 8, 2, 9],
       [1, 7, 9, 6],
       [8, 0, 7, 0],
       [5, 8, 9, 7]])

In [8]:
B

array([[0, 6, 8, 7],
       [4, 9, 6, 5],
       [8, 5, 4, 8],
       [7, 8, 5, 6]])

In [9]:
##Multiplicacion element wise A*B
## Multiplicacion regular de matrices
A @ B 

array([[111, 190, 149, 152],
       [142, 162, 116, 150],
       [ 56,  83,  92, 112],
       [153, 203, 159, 189]])

In [12]:
params = np.array([[3,4,5]])
samples = np.random.randint((10), size =(10,3))

In [13]:
params.shape, samples.shape

((1, 3), (10, 3))

In [15]:
sum(samples[0,:]* params)

array([ 6, 36, 35])

In [16]:
samples @ params.T

array([[77],
       [31],
       [83],
       [39],
       [64],
       [50],
       [67],
       [41],
       [52],
       [55]])

In [ ]:
## Need card_prices.csv in whatsapp